create table worker (id int8 generated by default as identity, nome varchar(255), salario_diario float8, primary key (id));
create table worker (id int8 generated by default as identity, nome varchar(255), salario_diario float8, primary key (id));
create table worker (id int8 generated by default as identity, nome varchar(255), salario_diario float8, primary key (id));
